sudo: required
services:
  - docker

before_install: 
  - docker build -t sravanthi698/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run sravanthi698/react-test npm test -- --coverage 

after_success:
  - docker build -t sravanthi698/multi-client ./client
  - docker build -t sravanthi698/multi-nginx ./nginx
  - docker build -t sravanthi698/multi-server ./server
  - docker build -t sravanthi698/multi-worker ./worker

#Log in to the Docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take  those images and push them to docker hub
  - docker push sravanthi698/multi-client
  - docker push sravanthi698/multi-nginx
  - docker push sravanthi698/multi-server
  - docker push sravanthi698/multi-worker
